target("qrest_data_hdf5")
    set_kind("static")
    add_files("hdf5_reader.cpp")
    add_files("hdf5_writer.cpp")
    add_packages("hdf5")
    add_syslinks("hdf5_cpp","hdf5")

target("test_qrest_data_hdf5")
    set_kind("binary")
    add_files("./test_*.cpp")
    add_deps("qrest_data_hdf5")
    add_packages("hdf5")
    add_syslinks("hdf5_cpp","hdf5")
